name: codacy-coverage-reporter

on: [pull_request]

jobs:
  install-and-test:
    name: install and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - name: Jest
      run: npm run test
    - name: Jest coverage comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-summary-path: ./coverage/coverage-final.json

